sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get --no-install-recommends install -y apt-utils ca-certificates -o Dpkg::Options::="--force-confold" --force-yes docker-engine

install:
  - make

script:
  - source venv/bin/activate
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
