---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "gateway-right"
      networkservicemesh.io/impl: "gw-routers"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "gateway-right"
        networkservicemesh.io/impl: "gw-routers"
    spec:
      containers:
        - name: universal-cnf-endpoint
          image: networkservicemesh/universal-cnf-vppagent:master
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command: ["mount", "-o", "rw,nosuid,nodev,noexec,relatime,remount", "/sys"]
          securityContext:
            privileged: true
          env:
            - name: TRACER_ENABLED
              value: "true"
          resources:
            requests:
              hugepages-2Mi: 100Mi
              memory: 100Mi
            limits:
              networkservicemesh.io/socket: 1
              hugepages-2Mi: 100Mi
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/universal-cnf/config.yaml
              subPath: config.yaml
              name: universal-cnf-config-volume
            - mountPath: /etc/vpp/vpp.conf
              subPath: vpp.conf
              name: universal-cnf-config-volume
            - mountPath: /dev/hugepages
              name: hugepages
      volumes:
        - name: universal-cnf-config-volume
          configMap:
            name: universal-cnf-gateway-right
        - name: hugepages
          emptyDir:
            medium: HugePages
metadata:
  name: gateway-right
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: universal-cnf-gateway-right
data:
  config.yaml: |
    initactions:
      - command:
          name: "vppctl"
          args: [
            "set int ip address TenGigabitEthernet1a/0/2 10.60.4.50/24",
            "set int state TenGigabitEthernet1a/0/2",
            ]
    endpoints:
    - name: "gw-routers"
      labels:
        app: "gw-right"
      ipam:
        prefixpool: "10.60.3.0/24"
        routes: ["10.60.4.0/24"]
      ifname: "endpoint0"
  vpp.conf: |
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      full-coredump
      cli-listen /run/vpp/cli.sock
      gid vpp
      poll-sleep-usec 1000
    }

    api-trace {
      on
    }

    api-segment {
      gid vpp
    }

    socksvr {
      default
    }

    cpu {

    }

    dpdk {
      dev 0000:1a:00.2
    }

    plugins {
      plugin default { disable }
      plugin dpdk_plugin.so { enable }
      plugin memif_plugin.so { enable }
    }
  
