---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "router-right"
      networkservicemesh.io/impl: "gw-routers"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "router-right"
        networkservicemesh.io/impl: "gw-routers"
    spec:
      containers:
        - name: universal-cnf-endpoint
          image: networkservicemesh/universal-cnf-vppagent:master
          imagePullPolicy: IfNotPresent
          env:
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
          volumeMounts:
            - mountPath: /etc/universal-cnf/config.yaml
              subPath: config.yaml
              name: universal-cnf-config-volume
      volumes:
        - name: universal-cnf-config-volume
          configMap:
            name: universal-cnf-router-right
metadata:
  name: router-right
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: universal-cnf-router-right
data:
  config.yaml: |
    initactions:
      - client:
          name: "gw-routers"
          ifname: "client0"
          routes: ["10.60.0.0/24", "10.60.1.0/24", "10.60.2.0/24"]
          labels:
            app: "gw-right"
    endpoints:
    - name: "gw-routers"
      labels:
        app: "router-right"
      ipam:
        prefixpool: "10.60.2.0/24"
        routes: ["10.60.3.0/24", "10.60.4.0/24"]
      ifname: "endpoint0"
