apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vppvswitch.fullname" . }}
  labels:
    app: {{ template "vppvswitch.name" . }}
    chart: {{ include "vppvswitch.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  1ccsp: |-
    create bridge-domain 1
    create bridge-domain 2

    bin memif_socket_filename_add_del add id 1 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif1.sock
    bin memif_socket_filename_add_del add id 2 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif2.sock

    create interface memif id 1 socket-id 1 master
    create interface memif id 2 socket-id 2 master

    set int l2 bridge {{ .Values.physintf1 }} 1
    set int l2 bridge memif1/1 1
    set int l2 bridge {{ .Values.physintf2 }} 2
    set int l2 bridge memif2/2 2

    set int mtu 9200 {{ .Values.physintf1 }}
    set int mtu 9200 {{ .Values.physintf2 }}
    set int state {{ .Values.physintf1 }} up
    set int state {{ .Values.physintf2 }} up
    set int state memif1/1 up
    set int state memif2/2 up
  2ccsp: |-
    create bridge-domain 1
    create bridge-domain 2

    bin memif_socket_filename_add_del add id 1 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif1.sock
    bin memif_socket_filename_add_del add id 2 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif2.sock
    bin memif_socket_filename_add_del add id 3 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif3.sock
    bin memif_socket_filename_add_del add id 4 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif4.sock

    create interface memif id 1 socket-id 1 master
    create interface memif id 2 socket-id 2 master
    create interface memif id 3 socket-id 3 master
    create interface memif id 4 socket-id 4 master

    set int l2 bridge {{ .Values.physintf1 }} 1
    set int l2 bridge memif1/1 1
    set int l2 bridge memif3/3 1
    set int l2 bridge {{ .Values.physintf2 }} 2
    set int l2 bridge memif2/2 2
    set int l2 bridge memif4/4 2
    set int mtu 9200 {{ .Values.physintf1 }}
    set int mtu 9200 {{ .Values.physintf2 }}
    set int state {{ .Values.physintf1 }} up
    set int state {{ .Values.physintf2 }} up
    set int state memif1/1 up
    set int state memif2/2 up
    set int state memif3/3 up
    set int state memif4/4 up
  3ccsp: |-
    create bridge-domain 1
    create bridge-domain 2

    bin memif_socket_filename_add_del add id 1 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif1.sock
    bin memif_socket_filename_add_del add id 2 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif2.sock
    bin memif_socket_filename_add_del add id 3 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif3.sock
    bin memif_socket_filename_add_del add id 4 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif4.sock
    bin memif_socket_filename_add_del add id 5 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif5.sock
    bin memif_socket_filename_add_del add id 6 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif6.sock

    create interface memif id 1 socket-id 1 master
    create interface memif id 2 socket-id 2 master
    create interface memif id 3 socket-id 3 master
    create interface memif id 4 socket-id 4 master
    create interface memif id 5 socket-id 5 master
    create interface memif id 6 socket-id 6 master

    set int l2 bridge {{ .Values.physintf1 }} 1
    set int l2 bridge memif1/1 1
    set int l2 bridge memif3/3 1
    set int l2 bridge memif5/5 1
    set int l2 bridge {{ .Values.physintf2 }} 2
    set int l2 bridge memif2/2 2
    set int l2 bridge memif4/4 2
    set int l2 bridge memif6/6 2

    set int mtu 9200 {{ .Values.physintf1 }}
    set int mtu 9200 {{ .Values.physintf2 }}

    set int state {{ .Values.physintf1 }} up
    set int state {{ .Values.physintf2 }} up
    set int state memif1/1 up
    set int state memif2/2 up
    set int state memif3/3 up
    set int state memif4/4 up
    set int state memif5/5 up
    set int state memif6/6 up
  setup.gate: |-
    create bridge-domain 1
    create bridge-domain 2

    bin memif_socket_filename_add_del add id 1 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif1.sock
    bin memif_socket_filename_add_del add id 2 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif2.sock
    bin memif_socket_filename_add_del add id 3 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif3.sock
    bin memif_socket_filename_add_del add id 4 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif4.sock
    bin memif_socket_filename_add_del add id 5 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif5.sock
    bin memif_socket_filename_add_del add id 6 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}memif6.sock

    create interface memif id 1 socket-id 1 master
    create interface memif id 2 socket-id 2 master
    create interface memif id 3 socket-id 3 master
    create interface memif id 4 socket-id 4 master
    create interface memif id 5 socket-id 5 master
    create interface memif id 6 socket-id 6 master

    set int l2 bridge {{ .Values.physintf1 }} 1
    set int l2 bridge memif1/1 1
    set int l2 bridge memif3/3 1
    set int l2 bridge memif5/5 1
    set int l2 bridge {{ .Values.physintf2 }} 2
    set int l2 bridge memif2/2 2
    set int l2 bridge memif4/4 2
    set int l2 bridge memif6/6 2

    set int mtu 9200 {{ .Values.physintf1 }}
    set int mtu 9200 {{ .Values.physintf2 }}

    set int state {{ .Values.physintf1 }} up
    set int state {{ .Values.physintf2 }} up
    set int state memif1/1 up
    set int state memif2/2 up
    set int state memif3/3 up
    set int state memif4/4 up
    set int state memif5/5 up
    set int state memif6/6 up
  startup.conf: |-
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      full-coredump
      cli-listen /run/vpp/cli.sock
      gid vpp
      startup-config /tmp/vpp_config/setup.gate
    }

    api-trace {
      on
    }

    api-segment {
      gid vpp
    }

    socksvr {
      default
    }

    cpu {
      main-core {{ .Values.mainCore }}
      corelist-workers {{ .Values.corelistWorkers }}
    }

    dpdk {
      dev default {
        num-rx-queues {{ .Values.rxqueues }}
      }
      dev {{ .Values.physpci1 }} dev {{ .Values.physpci2 }}
      no-multi-seg
      no-tx-checksum-offload
      socket-mem 124,0
    }

    plugins {
      plugin default { disable }
      plugin dpdk_plugin.so { enable }
      plugin memif_plugin.so { enable }
    }
