---
# Get chef and chef OpenStack cookbooks
- name: Resolve potential missing packages
  command: apt --fix-broken install -y

- name: update apt
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: get chef package
  yum:
    name: https://packages.chef.io/files/stable/chefdk/3.4.38/el/7/chefdk-3.4.38-1.el7.x86_64.rpm
  when: ansible_os_family == 'RedHat'

#- name: download chef package Debian
#  get_url:
#    url: https://packages.chef.io/files/stable/chefdk/3.2.30/ubuntu/18.04/chefdk_3.2.30-1_amd64.deb
#    dest: /root/chefdk_3.2.30-1_amd64.deb
#  when: ansible_os_family == 'Debian'

- name: get chef package
  apt:
    deb: https://packages.chef.io/files/stable/chefdk/3.2.30/ubuntu/18.04/chefdk_3.2.30-1_amd64.deb
  when: ansible_os_family == 'Debian'

- name: get openstack-chef code 
  git: 
    repo: https://git.openstack.org/openstack/openstack-chef
    version: "{{ openstack_chef_version }}"
    dest: /root/openstack-chef
    update: no
    
- name: run the berks command in the openstack-chef repo
  command: berks install
  args:
    chdir: /root/openstack-chef
    creates: /root/openstack-chef/cookbooks/

- name: move berks downloaded code to openstack-chef directory
  shell: mv cookbooks/ /root/openstack-chef
  args:
    chdir: /root/.berkshelf/
    creates: /root/openstack-chef/cookbooks/

- name: find openstack-common python.rb
  find:
    paths: /root/openstack-chef/cookbooks/
    recurse: yes
    patterns: "python.rb"
  register: common_python_rb 

- name: Update python to v3.6 for Ubuntu 18.04
  replace:
    dest: "{{item.path}}"
    regexp: "^.*python_runtime .* do.*$"
    replace: "  python_runtime '3.6' do"
  with_items: "{{common_python_rb['files']}}"
  when: ansible_distribution_release == 'bionic'

- name: find openstack-ops-database mariadb-client.rb
  find:
    paths: /root/openstack-chef/cookbooks/
    recurse: yes
    patterns: "mariadb-client.rb"
  register: mariadb_client_rb 

- name: Find orchestration identity registration recipe files from cookbooks
  command: find /root/openstack-chef/cookbooks/ -path  "*openstack-orchestration*/identity_registration.rb"
  # find: Cant use find module becausee it doesn't support regex of parent folders
  #   paths: /root/openstack-chef/cookbooks/
  #   recurse: yes
  #   patterns: "identity_registration.rb"
  register: orch_identity_registration_recipes

# TODO: file a bug for this
- name: remove admin endpoint references from openstack orchestration
  template:
    src: openstack-orchestration-identity_registration.rb
    dest: "{{ item }}"
  with_items: "{{ orch_identity_registration_recipes.stdout_lines }}"

- name: Find block storage identity registration recipe files from cookbooks
  command: find /root/openstack-chef/cookbooks/ -path  "*openstack-block-storage*/identity_registration.rb"
  # find: Cant use find module becausee it doesn't support regex of parent folders
  #   paths: /root/openstack-chef/cookbooks/
  #   recurse: yes
  #   patterns: "identity_registration.rb"
  register: block_identity_registration_recipes

- name: remove admin endpoint reference from openstack block storage
  lineinfile:
    path: "{{ item }}"
    regexp: "  admin: { url: admin_endpoint\\(\\'block-storage\\'\\) },"
    line: "#  admin: { url: admin_endpoint('block-storage') },"
  with_items: "{{ block_identity_registration_recipes.stdout_lines }}" 

- name: Update mysql ruby gem to 0.5.2 on Ubuntu 18.04
  replace:
    dest: "{{item.path}}"
    regexp: "^.*gem_version .*$"
    replace: "  gem_version '0.5.2'"
  with_items: "{{mariadb_client_rb['files']}}"
  when: ansible_distribution_release == 'bionic'

- name: ensure iSCSCI target directory exists on Ubuntu 18.04
  file:
    state: directory
    dest: /etc/target/
  when: ansible_distribution_release == 'bionic'

- name: Install chef client via the omnibus installer
  shell: curl -L https://omnitruck.chef.io/install.sh | bash
  args:
    creates: /usr/bin/chef-client
    
- name: Make /etc/chef directory
  file:
    state: directory
    dest: /etc/chef
    mode: 0664

- name: Move chef openstack secret to /etc/chef
  copy:
    src: /root/openstack-chef/.chef/encrypted_data_bag_secret
    dest: /etc/chef/openstack_data_bag_secret
    remote_src: True

# Update cookbooks, roles, and environments
- name: find the controller host address
  set_fact:
    host_0_address: "{{hostvars[groups['all'][0]].ansible_bond0.ipv4.address}}"

- name: Locally upload the chef recieps
  command: knife cookbook upload -a -z --include-dependencies --cookbook-path cookbooks/
  args:
    chdir: /root/openstack-chef/
    creates: /root/openstack-chef/cookbooks/openstack-common

- name: install updated environment file
  template:
    src: multinode.json
    dest: /root/openstack-chef/environments/multinode.json

- name: create openstack neutron config directory
  file:
    state: directory
    dest: /etc/neutron
    mode: 0755

- name: create an empty neutron plugin.ini file
  file:
    state: touch
    dest: /etc/neutron/plugin.ini
    mode: 0755

- name: create a dashboard secrets directory
  file:
    state: directory
    dest: /var/lib/openstack-dashboard
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: create a dashboard secrets file for Debian
  copy:
    content: 'aaWN2w6bcIHFUMZZ7aT5uBSPxnDZpOujHjHHx0HzNbnOopD2wrmYqbWlQsTUO66D'
    dest: /var/lib/openstack-dashboard/secret_key
    mode: 0600
  when: ansible_os_family == 'Debian'

- name: Add python upate for chef Debian deployments
  apt:
    update_cache: yes
    name: ['python-pip','python3-pip']
  when: ansible_os_family == 'Debian'

- name: Ensure pip 18.0 for chef Debian
  pip:
    name: pip
    version: 18.0
    executable: 'pip3'
    state: forcereinstall
  when: ansible_os_family == 'Debian'

- name: Install python api pre-requisites
  pip:
    name: ['pycparser','cffi']

- name: Update the multinode-controller role - VPP
  template:
    src: multinode-controller.json
    dest: /root/openstack-chef/roles/multinode-controller.json
  when: vpp_network

- name: Update the multinode-controller role - non-VPP
  template:
    src: multinode-controller-novpp.json
    dest: /root/openstack-chef/roles/multinode-controller.json
  when: not vpp_network

- name: Update the multinode-controller storage role
  template:
    src: multinode-storage.json
    dest: /root/openstack-chef/roles/multinode-storage.json
  when: vpp_network

- name: Update the multinode-compute role - VPP
  template:
    src: multinode-compute.json
    dest: /root/openstack-chef/roles/multinode-compute.json
  when: vpp_network

- name: Update the multinode-compute role - non-VPP
  template:
    src: multinode-compute-novpp.json
    dest: /root/openstack-chef/roles/multinode-compute.json
  when: not vpp_network

#- name: address bug in Chef rabbit module mis-understand 3.6 vs 3.7
#  lineinfile:
#    dest: /root/openstack-chef/cookbooks/rabbitmq/providers/plugin.rb
#    regexp: '^.*rabbitmq-plugins list -q -e.*$'
#    line: |
#                   "rabbitmq-plugins list -e '#{name}\\b'"
#    
- name: Launch Chef based OpenStack installer on First (controller) node
  command: chef-client -z -E multinode -r 'role[multinode-controller]'
  args:
    chdir: /root/openstack-chef
  when: host_0_address == inventory_hostname
 
- name: Add Chef based OpenStack storage installer on First (controller) node
  command: chef-client -z -E multinode -r 'role[multinode-storage]'
  args:
    chdir: /root/openstack-chef
  when: host_0_address == inventory_hostname
 
- name: Launch Chef based OpenStack installer on Other (compute) nodes
  command: chef-client -z -E multinode -r 'role[multinode-compute]'
  args:
    chdir: /root/openstack-chef
  when: not host_0_address == inventory_hostname
