#! /bin/bash

apt-get update -y
apt-get install --allow-unauthenticated -y make gcc libcurl4-openssl-dev python-pip bridge-utils apt-transport-https ca-certificates
pip install jsonschema

apt-get -y install linux-headers-$(uname -r)
