#! /bin/bash

VPP_VERSION="18.10-release"
artifacts=()
vpp=(vpp vpp-dbg vpp-dev vpp-lib vpp-plugins)
if [ -z "${VPP_VERSION-}" ]; then
    artifacts+=(${vpp[@]})
else
    artifacts+=(${vpp[@]/%/=${VPP_VERSION-}})
fi
curl -s https://packagecloud.io/install/repositories/fdio/release/script.deb.sh | bash
apt-get install -y "${artifacts[@]}"
