---
# ./ EQUINIX METAL create vlan and save vlan ids
# ./ EQUINIX METAL disbond interfaces
# ./ EQUINIX METAL assign vlan

- hosts: localhost
  vars:
    facility: "{{ lookup('env','PACKET_FACILITY') }}"
    deploy_env: "{{ lookup('env','K8S_DEPLOY_ENV') }}"
    server_list: "{{ lookup('env','SERVER_LIST') }}"
    project_name: "{{ lookup('env','PROJECT_NAME') }}"
    vlans:
      vlan1:
        interface: eth2
      vlan2:
        interface: eth3
  roles:
    - packet_l2

- hosts: all
  vars:
    config_network_bonds: true
    config_network_bridges: true
    config_network_interfaces: true
    enable_configured_interfaces_after_defining: false
    dns_nameservers:
      - "{{ ansible_dns.nameservers[0] }}"
      - "{{ ansible_dns.nameservers[0] }}"
    network_bonds:
      - name: 'bond0'
        configure: true
        enable: false
        method: 'static'
        address: "{{ ansible_bond0.ipv4.address }}"
        netmask: "{{ ansible_bond0.ipv4.netmask }}"
        gateway: "{{ ansible_default_ipv4.gateway }}"
        parameters:
          - param: 'bond-downdelay'
            val: '200'
          - param: 'bond-miimon'
            val: '100'
          - param: 'bond-mode'
            val: '4'
          - param: 'bond-updelay'
            val: '200'
          - param: 'bond-xmit_hash_policy'
            val: 'layer3+4'
          - param: 'bond-lacp-rate'
            val: '1'
        slaves:
          - 'eno1'
      - name: 'bond0:0'
        configure: true
        enable: false
        method: 'static'
        address: "{{ ansible_bond0_0.ipv4.address }}"
        netmask: "{{ ansible_bond0_0.ipv4.netmask }}"
        parameters:
          - param: 'post-up'
            val: "route add -net 10.0.0.0/8 gw {{ ansible_bond0_0.ipv4.network }}"
          - param: 'post-down'
            val: "route del -net 10.0.0.0/8 gw {{ ansible_bond0_0.ipv4.network }}"
    network_interfaces:
      - name: 'eno1'
        configure: true
        enable: false
        method: 'manual'
        parameters:
          - param:
            val: 'bond-master bond0'
      - name: 'eno2'
        configure: true
        enable: false
        method: 'manual'
        parameters:
          - param: 'pre-up'
            val: 'sleep 4'
      - name: 'eno3'
        configure: true
        enable: false
        method: 'manual'
        parameters:
          - param: 'pre-up'
            val: 'sleep 4'
      - name: 'eno4'
        configure: true
        enable: false
        method: 'manual'
        parameters:
          - param: 'pre-up'
            val: 'sleep 4'
    network_bridges:
      - name: 'ltes5c'
        configure: true
        enable: false
        method: 'manual'
        parameters:
          - param: 'bridge_stp'
            val: 'off'
        ports:
          - 'eno3'
      - name: 'ltes5u'
        configure: true
        enable: false
        method: 'manual'
        parameters:
          - param: 'bridge_stp'
            val: 'off'
        ports:
          - 'eno4'
  pre_tasks:
  - name: Apt update
    apt:
      update_cache: yes
  - name: Install Bridge utils
    apt: 
      name: bridge-utils
  post_tasks:
  - name: Reboot server
    reboot:
      post_reboot_delay: 60
  roles:
    - mrlesmithjr.config-interfaces
