cnf_ipsec:
  cnfs: 4
  main_core: ['6','8','34','36']
  worker_cores: ['10,38','12,40','14,42','16,44']

cnf_3c2n-csp:
  cnfs: 6
  main_core: ['6','8','10','34','36','38']
  worker_cores: ['12,40','14,42','16,44','18,46','20,48','22,50']

cnf_3c2n-csc:
  cnfs: 6
  main_core: ['6','8','10','34','36','38']
  worker_cores: ['12,40','14,42','16,44','18,46','20,48','22,50']

cnf: "{{ lookup('vars','cnf_' + use_case) }}"
