# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1604"
  #config.vm.box = "roboxes/ubuntu1604"

  #config.vm.provision "shell", path: "v_bng_install.sh", privileged: true
  #config.vm.provision "shell", path: "test_script.sh", privileged: true
  config.vm.synced_folder './', '/vagrant'
  config.vm.define vm_name = "vBNG" do |config|
    config.vm.hostname = vm_name
    config.vm.provider :libvirt do |v|
      v.cpus = 4
      v.numa_nodes = [
        {:cpus => "0-3", :memory => "4096"}
      ]
      #v.memory = 4096
      #v.memory = 2048
      v.memorybacking :hugepages
      #v.memorybacking :nosharepages
      #v.memorybacking :locked
      #v.memorybacking :source, :type => 'file'
      v.memorybacking :access, :mode => 'shared'
      #v.memorybacking :allocation, :mode => 'immediate'
    end
    #config.vm.network :private_network, :ip => "10.3.0.10"
    #config.vm.network :private_network, :ip => "10.1.0.10"
    #config.vm.network :private_network, :ip => "10.0.101.10"
    #config.vm.network :private_network,
    #  :libvirt__tunnel_type => 'client',
    #  :libvirt__tunnel_port => '11113'
    #config.vm.network :private_network,
    #  :libvirt__tunnel_type => 'client',
    #  :libvirt__tunnel_port => '11114'
  end
end
