apiVersion: v1
kind: ConfigMap
metadata:
  name: cnf-testbed-sriov-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "vfio_ports",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["1572"],
                    "drivers": ["vfio-pci"]
                }
            }
        ]
    }
