---
- name: Check NSM status
  command: helm list | grep DEPLOYED | grep nsm-system
  changed_when: false
  ignore_errors: true
  register: nsm_status

- name: Install NSM is necessary
  command: chdir={{ role_path }} helm install --namespace=nsm-system files/nsm/
  when: nsm_status.stdout == ""
