Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
  config.vm.synced_folder './', '/vagrant'
  config.vm.define vm_name = "Pktgen" do |config|
    config.vm.hostname = vm_name
    config.vm.provider :libvirt do |v|
      v.cpus = 4
      v.memory = 4096
    end
    #config.vm.network :private_network, :ip => "40.30.20.10"
    #config.vm.network :private_network, :ip => "40.30.20.11"
    config.vm.network :private_network,
      :libvirt__tunnel_type => 'server',
      :libvirt__tunnel_port => '11113',
      :mac => 'de:ad:00:00:00:00'
    config.vm.network :private_network,
      :libvirt__tunnel_type => 'server',
      :libvirt__tunnel_port => '11114',
      :mac => 'be:ef:00:00:00:00'
  end
end
