Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.synced_folder './', '/vagrant'
  config.vm.define vm_name = "Pktgen" do |config|
    config.vm.hostname = vm_name
    config.vm.provider :libvirt do |v|
      v.cpus = 3
      v.numa_nodes = [
        {:cpus => "0-2", :memory => "4096"}
      ]
      v.memorybacking :hugepages
      v.memorybacking :access, :mode => 'shared'
    end
  end
end
