---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "simple-client"
      networkservicemesh.io/impl: "packet-filtering"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "simple-client"
        networkservicemesh.io/impl: "packet-filtering"
    spec:
      containers:
        - name: alpine-img
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ['tail', '-f', '/dev/null']
      initContainers:
        - name: nsm-init-container
          image: networkservicemesh/nsm-init:master
          imagePullPolicy: IfNotPresent
          env:
            - name: NS_NETWORKSERVICEMESH_IO
              value: packet-filtering
          resources:
            limits:
              networkservicemesh.io/socket: "1"
metadata:
  name: simple-client
