---
- hosts: localhost
  vars:
    reuse: false

  pre_tasks:
  - name: Check KUBECONFIG env. variable
    local_action: stat path="{{ lookup('env', 'KUBECONFIG') }}"
    register: kubeconfig

  - name: Verify that kubeconfig file exists
    fail:
      msg: "Kubeconfig file not found at: {{ lookup('env', 'KUBECONFIG') }}"
    when: not kubeconfig.stat.exists

  - name: Check if Kubectl is installed
    command: which kubectl
    changed_when: false
    ignore_errors: true
    register: kubectl_installed

  - name: Install Kubectl if necessary
    shell: "chdir=/tmp/ {{ item }}"
    with_items:
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
    when: kubectl_installed.rc not in [ 0 ]

  - name: Check if Helm is installed
    command: which helm
    changed_when: false
    ignore_errors: true
    register: helm_installed

  - name: Install Helm if necessary
    shell: chdir=/tmp/ {{ item }}
    with_items:
      - curl -LO https://git.io/get_helm.sh
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - rm get_helm.sh
      - helm init --upgrade
    when: helm_installed.rc not in [ 0 ]

  - name: Check for existing CNFs
    shell: "kubectl get deployments --no-headers | wc -l"
    changed_when: false
    register: cnf_count

  - name: Remove Packet Filter CNFs
    command: "kubectl delete deployment {{ item }}"
    with_items:
      - ucnf-client
      - simple-client
      - packet-filter
      - gateway
    ignore_errors: true
    when: cnf_count.stdout|int > 0 and not reuse

  roles:
    - nsm_helm_install
    - nsm_pf_cnf_install
