---
# ./ PACKET create vlan and save vlan ids
# ./ PACKET disbond interfaces
# ./ PACKET assign vlan

- hosts: localhost
  vars:
    #    server_list: quadtestb-07,quadtestb-08   
    deploy_env: test1
    vlans:
      vlan1:
        interface: eth1
      vlan2:
        interface: eth2
      vlan3:
        interface: eth3
  roles:
    - packet_l2
