---
- hosts: localhost
  pre_tasks:
  - name: Apt update
    apt:
      update_cache: yes
  - name: Install Vlan Package
    apt: 
      name: vlan
  - name: Get bond interface slaves
    setup:
      filter: "{{ ansible_bond0.slaves }}"
  - name: Get dns servers
    setup: 
      filter: "{{ ansible_dns.nameservers }}"
  - name: Get Bond0 Public IP
    setup: 
      filter: "{{ ansible_bond0.ipv4.address }}"
  - name: Get bond0 netmask
    setup: 
      filter: "{{ ansible_bond0.ipv4.netmask }}"
  - name: Echo bond0 netmask
    setup: 
      filter: "{{ ansible_default_ipv4.gateway }}"
  - name: Get bond0 internal address
    setup: 
      filter: "{{ ansible_bond0_0.ipv4.address }}"
  - name: Get bond0 internal netmask
    setup:
      filter: "{{ ansible_bond0_0.ipv4.netmask }}"
  - name: Get bond0 internal gw
    setup:
      filter: "{{ ansible_bond0_0.ipv4.network }}"
  - name: Get trex_port_0 pci id
    setup: 
      filter: "{{ ansible_enp2s0d1.pciid }}"
  - name: Get trex_port_1 pci id
    setup: 
      filter: "{{ ansible_eno2.pciid }}"
  post_tasks:
  - name: Reboot Server
    reboot:
    
  vars:
    mellanox_4_4: true
    mellanox_4_1: false
    cnf: true
    vnf: false
    baseline: false
    hugepages: 10240
    config_network_bonds: true
    config_network_bridges: false
    config_network_interfaces: true
    enable_configured_interfaces_after_defining: true
    dns_nameservers:
      - "{{ ansible_dns.nameservers[0] }}"
      - "{{ ansible_dns.nameservers[0] }}"
    network_bonds:
      - name: 'bond0'
        configure: true
        method: 'static'
        address: "{{ ansible_bond0.ipv4.address }}"
        netmask: "{{ ansible_bond0.ipv4.netmask }}"
        gateway: "{{ ansible_default_ipv4.gateway }}"
        parameters:
          - param: 'bond-downdelay'
            val: '200'
          - param: 'bond-miimon'
            val: '100'
          - param: 'bond-mode'
            val: '4'
          - param: 'bond-updelay'
            val: '200'
          - param: 'bond-xmit_hash_policy'
            val: 'layer3+4'
          - param: 'bond-lacp-rate'
            val: '1'
        slaves:
          - "{{ ansible_bond0.slaves[0] }}"
      - name: 'bond0:0'
        configure: true
        method: 'static'
        address: "{{ ansible_bond0_0.ipv4.address }}"
        netmask: "{{ ansible_bond0_0.ipv4.netmask }}"
        parameters:
          - param: 'post-up'
            val: "route add -net 10.0.0.0/8 gw {{ ansible_bond0_0.ipv4.network }}"
          - param: 'post-down'
            val: "route del -net 10.0.0.0/8 gw {{ ansible_bond0_0.ipv4.network }}"
    network_interfaces:
      - name: "{{ ansible_bond0.slaves[0] }}"
        configure: true
        method: 'manual'
        parameters:
          - param:
            val: 'bond-master bond0'
      - name: "{{ ansible_bond0.slaves[1] }}"
        configure: true
        method: 'manual'
        parameters:
          - param: 'pre-up'
            val: 'sleep 4'
      - name: "{{ ansible_bond0.slaves[1] }}.1030"
        configure: true
        method: 'static'
        address: '172.16.99.31'
        netmask: '255.255.255.0'
  roles:
    - mrlesmithjr.config-interfaces
    - grub
    - mellanox
    - vpp
    - vfs
