Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1604"

  config.vm.provision "shell", path: "v_packetgen_install.sh", privileged: false
  config.vm.synced_folder './', '/vagrant'
  config.vm.define vm_name = "vDNSgen" do |config|
    config.vm.hostname = vm_name
    config.vm.provider :libvirt do |v|
      v.cpus = 3
      v.memory = 4096
    end
    config.vm.network :private_network, :ip => "40.30.20.90", libvirt__driver_queues:2
  end
end
