---
- name: find the controller host address
  set_fact:
    host_0_address: "{{hostvars[groups['all'][0]].ansible_bond0.ipv4.address}}"

#- name: Enable use of vfio-pci driver
#  replace:
#    path: /lib/systemd/system/vpp.service
#    regexp: 'uio_pci_generic'
#    replace: 'vfio-pci'
#    backup: no
#  when: ansible_os_family == "Debian"

- name: create VPP directory
  file:
    state: directory
    dest: /etc/vpp
    mode: 0755

- name: add uplink vpp tap startup script
  template:
    src: uplink.conf
    dest: /etc/vpp/uplink.conf
  when: inventory_hostname == host_0_address

- name: update vpp startup script for l3
  template:
    src: startupl3.conf
    dest: /etc/vpp/startup.conf
  when: inventory_hostname == host_0_address

- name: update vpp startup script compute
  template:
    src: startup.conf
    dest: /etc/vpp/startup.conf
  when: not inventory_hostname == host_0_address

- name: make sure vfio-pci loads on startup
  template:
    src: vfio-pci.conf
    dest: /etc/modules-load.d/vfio-pci.conf

- name: Docker start vppcontainer (Intel)
  docker_container:
    name: vppcontainer
    image: soelvkaer/vppcontainer:latest
    state: started
    network_mode: host
    privileged: true
    restart_policy: always
    devices:
      - "/dev/hugepages/:/dev/hugepages/:rwm"
    volumes:
      - /etc/vpp/:/etc/vpp/
      - /dev:/dev
