- name: Show vlan data before create
  debug: var=vlans
 
- name: Create or find a Packet VLAN
  command: ruby /packet_api/l2_packet_networking.rb --create-vlan="{{ deploy_env }}{{ item.key }}" --project-name="{{ project_name }}" --packet-url='api.packet.net' --facility="{{ facility }}"
  with_dict: "{{ vlans }}"
  register: vlandata
  
- name: store vlan id 
  set_fact:
    vlans: "{{ vlans|combine({item.item.key: {'vid': item.stdout, 'desc': deploy_env + item.item.key }}, recursive=True) }}"
  with_items: "{{ vlandata.results }}"

- name: ensure host_facts directory exists
  file:
    dest: /etc/ansible/facts.d
    state: directory

- name: write vlan id to host_fact file
  lineinfile:
    dest: /etc/ansible/facts.d/vlans.fact
    create: true
    line: '"{{vlans}}"'
    mode: 0644
  
- name: updated vlan data
  debug: var=vlans

- name: Remove interface from bond0, for all specifed nodes
  command: ruby /packet_api/l2_packet_networking.rb --server={{ item[0] }} --disbond-interface={{ vlans[item[1]].interface }} --project-name="{{ project_name }}"  --packet-url='api.packet.net'
  with_nested:
    - "{{ server_list.split(',') }}"
    - "{{ vlans }}"

- name: Assign vlan to interface
  command: ruby /packet_api/l2_packet_networking.rb --server={{ item[0] }} --assign-vlan-id={{ vlans[item[1]].vid }} --assign-vlan-port={{ vlans[item[1]].interface }} --project-name="{{ project_name }}" --packet-url='api.packet.net'
  with_nested:
    - "{{ server_list.split(',') }}"
    - "{{ vlans }}"
